### PR TITLE
deps: update Nomad dep to v1.5.3

### LINKED ISSUE #479: Levant is not up to date with nomad api version
Hello guys,

Levant version is not up to date with latest nomad api version.

When I'm trying to render a sidercar_service with a meta block from the documentation https://developer.hashicorp.com/nomad/docs/job-specification/sidecar_service I'm getting the error below:

```
Error getting job struct: Error parsing job file from render.nomad:
render.nomad:61,11-15: Unsupported block type; Blocks of type "meta" are not expected here.
```
It's normal because this block it's only supported in the 1.5.x version. You can have more informations [here](https://developer.hashicorp.com/nomad/docs/v1.4.x/job-specification/sidecar_service) and [here](https://github.com/hashicorp/levant/blob/v0.3.2/go.mod#L10)
 
**Output of `levant version`:**

```
v0.3.2
```

**Output of `consul version`:**

```
v1.15.2+ent
```

**Output of `nomad version`:**

```
v1.5.3
```

Can we have more release of levant compatible with the latest version of nomad?

Thx.

### PR DESCRIPTION
**Pull request by jrasell**
closes #479

### CODE REVIEW

**Comment by lgfa29** [comment]
CI is sad due to a breaking change in `nomad.Jobs().Dispatch` 😢

**Comment by jrasell** [comment]
> @jrasell any plan to fix the code soon :) ?
> 
> ```
> Error: levant/dispatch.go:41:65: not enough arguments in call to l.nomad.Jobs().Dispatch
> 	have (string, map[string]string, []byte, nil)
> 	want (string, map[string]string, []byte, string, *"github.com/hashicorp/nomad/api".WriteOptions)
> make: *** [GNUmakefile:21: pkg/linux_amd64/levant] Error 2
> Error: Process completed with exit code 2.
> ```

Yes there is when I have a moment hopefully today.

**Review by angrycub — APPROVED** [review]
:+1:

**Comment by Lord-Y** [comment]
Hello @jrasell , sorry to bother. You update everything and I thank you for that but we still have no new version [here](https://releases.hashicorp.com/levant). Is it normal?

**Pull request merged**
