### PR TITLE
deps: update Nomad jobspec dep to 1.0.0

### PR DESCRIPTION
**Pull request by jrasell**
This change updates the internal jobspec parsing to reflect Nomad 1.0.0 and includes updates to the Nomad API and Consul API packages.

### CODE REVIEW

**Review by cgbaker — APPROVED** [review]
lgtm

in case you didn't notice, we updated the TF provider to pull the jobspec in. it required a little bit of dependency-wrangling on our part because of some TF stuff, not sure what the impact would be in levant:
https://github.com/hashicorp/terraform-provider-nomad/pull/161

**Review by lgfa29 — APPROVED** [review]
What @cgbaker said 😄

**Comment by jrasell** [comment]
@cgbaker and @lgfa29 Levant suffers compared to the provider as it passes around the API job object and the import is screwed up by the API replace line within Nomad's `go.mod` along with the API being its own module and so within the vendor directory:

```
Cannot use 'jobspec.Parse(tpl)' (type (*"github.com/hashicorp/nomad/vendor/github.com/hashicorp/nomad/api".Job, error)) as type *"github.com/hashicorp/nomad/api".Job
```

**Review by cgbaker — APPROVED** [review]
sweet. this should make these a lot easier going forward, including potentially being automatable.

**Pull request merged**
