### PR TITLE
Re-add possibility to use different types

### LINKED ISSUE #378: parseTFVars supports only strings
**Description**

I'm not able to use the "type" / "description" keywords in the definition of a variable.   
It stopped working at commit be00465ca643af991d88f69b44608cdbc7353a1d with the introduction of 
```
type terraformVar struct {
	Key     string `hcl:"key,label"`
	Default string `hcl:"default"`
}
```
Which limits the type of a variable to string: i.e. lists aren't supported anymore and the "description" field isn't either.  
Any particular reason why the support for lists was dropped @jrasell ?

Using the following example Nomad job / var file:   
```
variable "resources_cpu_string" {
  description = "the CPU in MHz to allocate to the task group"
  type        = "string"
  default     = 250
}

variable "resources_cpu_list" {
  type        = "list"
  default     = [1,2,3]
}
```
And a random non-valid Nomad job:
```
job "ingress-example" {

  datacenters = ["dc1"]

  group "ingress-group" {

    network {
      mode = "bridge"
    }
  }
}
```
Throws:
```
./bin/levant render -var-file=test.tf gateway.nomad    
[ERROR] levant/command: test.tf:2,3-14: Unsupported argument; An argument named "description" is not expected here., and 3 other diagnostic(s)
```

**Output of `levant version`:**
```
0.3.0-beta1
```

### PR DESCRIPTION
**Pull request by gpaggi**
Fixes #378

Perhaps it would be good to enhance the TF template render test to cover lists as well

### CODE REVIEW

**Review by jrasell — APPROVED** [review]
LGTM thanks @gpaggi. 

I wont be able to merge this in until the CLA is fully signed. It is currently awaiting "Gabriele Paggi" which is a user not found on GitHub. If all commits should have been made by "gpaggi" I would suggest resetting these commits locally and force pushing a single commit to the branch using the "gpaggi" user.

**Comment by gpaggi** [comment]
@jrasell I'm afraid this won't be enough
```
Default     string `hcl:"default"`
```
Still expects a string. I'm having a look at using interface{} and use type assertions in parseTFVars but I'm not familiar with gohcl or cty, so it may take a while :)
I'll send an updated force-pushed commit later, which will also fix the CLA.

**Comment by gpaggi** [comment]
Had a better look at it and it's not as straight forward as I hoped.  
For a simple
```
variable "environments" {
  type = "list"
  default = ["pre-prod", "prod"]
}
```
And
```
type terraformVar struct {
	Key         string      `hcl:"key,label"`
	Default     interface{} `hcl:"default,attr"`
	Type        string      `hcl:"type,optional"`
	Description string      `hcl:"description,optional"`
}
```
gohcl.DecodeBody marshals the interface{} into hcl.Attribute which contains a slice of hclsyntax.Expression, which is handy if you have to support rich expressions like in Terraform but not really needed here.
All in all I haven't found an easy way to support basic types like int, string, []int and []string.

In the current implementation of the HCL parser in Levant it supports only strings and, since you have also support for yaml and json, have you considered dropping support for .tf files altogether?

**Comment by jrasell** [comment]
Closed in favour of #380. Thanks very much for your initial work on this @gpaggi, please let me know if you have any feedback on the merged fix.

**Pull request closed without merging**
